// Module6_FrontendDevelopmentBasics/HandsOn_8/student-portal-vue/src/components/coursecard.vue
<template>
  <div class='course-card'>
    <div>
      <h3>
        <RouterLink :to='`/courses/${id}`'>{{ name }}</RouterLink>
      </h3>
      <div class='course-code'>{{ code }}</div>
      <p>{{ description }}</p>
    </div>
    <div class='course-footer'>
      <span class='course-credits'>Credits: {{ credits }}</span>
      <button 
        type='button' 
        class='action-btn' 
        @click='handleEnroll'
        :disabled='isEnrolled'
      >
        {{ isEnrolled ? 'Enrolled' : 'Enroll' }}
      </button>
    </div>
  </div>
</template>

<script setup>
import {computed} from 'vue';
import {RouterLink, useRouter} from 'vue-router';
import {useEnrollmentStore} from '@/stores/enrollment';

const props=defineProps({
  id:Number,
  name:String,
  code:String,
  credits:Number,
  grade:String,
  description:String
});

const router=useRouter();
const enrollmentStore=useEnrollmentStore();

const isEnrolled=computed(()=>{
  return enrollmentStore.enrolledCourses.some(c=>c.id===props.id);
});

function handleEnroll(){
  enrollmentStore.enroll({
    id:props.id,
    name:props.name,
    code:props.code,
    credits:props.credits,
    description:props.description
  });
  router.push('/profile');
}
</script>

// Module6_FrontendDevelopmentBasics/HandsOn_10/student-portal-react/src/components/coursecard.jsx
import React from 'react';
import {Link, useNavigate} from 'react-router-dom';
import {useDispatch, useSelector} from 'react-redux';
import {enrollCourseThunk, selectEnrolledCourses} from '../store/courseSlice';

export default function CourseCard(course){
  const {id, name, code, credits, description}=course;
  const dispatch=useDispatch();
  const navigate=useNavigate();
  const enrolledCourses=useSelector(selectEnrolledCourses);
  
  const isEnrolled=enrolledCourses.some(c=>c.id===id);

  const handleEnroll=async()=>{
    await dispatch(enrollCourseThunk({studentId:1, course})).unwrap();
    navigate('/profile');
  };

  return (
    <div className='course-card'>
      <div>
        <h3>
          <Link to={`/courses/${id}`}>{name}</Link>
        </h3>
        <div className='course-code'>{code}</div>
        <p>{description}</p>
      </div>
      <div className='course-footer'>
        <span className='course-credits'>Credits: {credits}</span>
        <button 
          type='button' 
          className='action-btn' 
          onClick={handleEnroll}
          disabled={isEnrolled}
        >
          {isEnrolled ? 'Enrolled' : 'Enroll'}
        </button>
      </div>
    </div>
  );
}
