// Module6_FrontendDevelopmentBasics/HandsOn_7/student-portal-angular/src/app/components/student-profile/student-profile.component.ts
import {Component} from '@angular/core';
import {CommonModule} from '@angular/common';
import {ReactiveFormsModule, FormGroup, FormControl, Validators} from '@angular/forms';

@Component({
  selector:'app-student-profile',
  standalone:true,
  imports:[CommonModule, ReactiveFormsModule],
  templateUrl:'./student-profile.component.html',
  styleUrl:'./student-profile.component.css'
})
export class StudentProfileComponent{
  profileForm=new FormGroup({
    name:new FormControl('Alex Johnson', [Validators.required]),
    email:new FormControl('alex.j@university.edu', [Validators.required, Validators.email]),
    semester:new FormControl(6, [Validators.required, Validators.min(1), Validators.max(8)])
  });

  onSubmit():void{
    if(this.profileForm.valid){
      console.log('Form Submitted Successfully:', this.profileForm.value);
    }
  }
}
<div class='profile-card'>
  <h2>Student Profile (Reactive Forms)</h2>
  <form [formGroup]='profileForm' (ngSubmit)='onSubmit()' class='profile-form'>
    <div class='form-group'>
      <label for='name'>Full Name</label>
      <input 
        id='name' 
        type='text' 
        formControlName='name' 
        [class.invalid]='profileForm.get("name")?.invalid && profileForm.get("name")?.touched'
      />
      <div *if='profileForm.get("name")?.invalid && profileForm.get("name")?.touched' class='error-msg'>
        Name is required.
      </div>
    </div>

    <div class='form-group'>
      <label for='email'>Email Address</label>
      <input 
        id='email' 
        type='email' 
        formControlName='email' 
        [class.invalid]='profileForm.get("email")?.invalid && profileForm.get("email")?.touched'
      />
      <div *ngIf='profileForm.get("email")?.invalid && profileForm.get("email")?.touched' class='error-msg'>
        Enter a valid email address.
      </div>
    </div>

    <div class='form-group'>
      <label for='semester'>Current Semester (1-8)</label>
      <input 
        id='semester' 
        type='number' 
        formControlName='semester' 
        [class.invalid]='profileForm.get("semester")?.invalid && profileForm.get("semester")?.touched'
      />
      <div *ngIf='profileForm.get("semester")?.invalid && profileForm.get("semester")?.touched' class='error-msg'>
        Semester must be between 1 and 8.
      </div>
    </div>

    <button type='submit' class='submit-btn' [disabled]='profileForm.invalid'>Save Profile</button>
  </form>
</div>

// Module6_FrontendDevelopmentBasics/HandsOn_6/student-portal-react/src/components/studentprofile.jsx
import React, {useState} from 'react';

export default function StudentProfile(){
  const [profile, setProfile]=useState({
    name:'Alex Johnson',
    email:'alex.j@university.edu',
    semester:'6'
  });

  const handleChange=(e)=>{
    const {name, value}=e.target;
    setProfile(prev=>({
      ...prev,
      [name]:value
    }));
  };

  return (
    <div class='profile-card'>
      <h2>Student Profile</h2>
      <form class='profile-form' onSubmit={e=>e.preventDefault()}>
        <div class='form-group'>
          <label htmlFor='name'>Full Name</label>
          <input 
            type='text' 
            id='name' 
            name='name' 
            value={profile.name} 
            onChange={handleChange} 
          />
        </div>
        <div class='form-group'>
          <label htmlFor='email'>Email Address</label>
          <input 
            type='email' 
            id='email' 
            name='email' 
            value={profile.email} 
            onChange={handleChange} 
          />
        </div>
        <div class='form-group'>
          <label htmlFor='semester'>Current Semester</label>
          <input 
            type='number' 
            id='semester' 
            name='semester' 
            value={profile.semester} 
            onChange={handleChange} 
          />
        </div>
      </form>
    </div>
  );
}
