// Module6_FrontendDevelopmentBasics/HandsOn_6/student-portal-react/src/components/header.jsx
import React from 'react';
import {Link} from 'react-router-dom';
import {useSelector} from 'react-redux';

export default function Header(props){
  const enrolledCourses=useSelector(state=>state.enrollment.enrolledCourses);

  return (
    <header>
      <h1>
        <Link to='/'>{props.siteName}</Link>
      </h1>
      <nav>
        <ul>
          <li><Link to='/'>Home</Link></li>
          <li><Link to='/courses'>Courses</Link></li>
          <li><Link to='/profile'>Profile</Link></li>
          <li>
            <span className='enrolled-badge'>
              Enrolled: {enrolledCourses.length}
            </span>
          </li>
        </ul>
      </nav>
    </header>
  );
}

// Module6_FrontendDevelopmentBasics/HandsOn_8/student-portal-vue/src/components/header.vue
<template>
  <header>
    <h1>
      <RouterLink to='/'>Student Portal</RouterLink>
    </h1>
    <nav>
      <ul>
        <li><RouterLink to='/'>Home</RouterLink></li>
        <li><RouterLink to='/courses'>Courses</RouterLink></li>
        <li><RouterLink to='/profile'>Profile</RouterLink></li>
        <li>
          <span class='enrolled-badge'>
            Enrolled: {{ enrollmentStore.enrolledCourses.length }}
          </span>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script setup>
import {RouterLink} from 'vue-router';
import {useEnrollmentStore} from '@/stores/enrollment';

const enrollmentStore=useEnrollmentStore();
</script>
