// Module6_FrontendDevelopmentBasics/HandsOn_8/student-portal-vue/src/components/header.vue
<template>
  <header>
    <h1>
      <RouterLink to='/'>Student Portal</RouterLink>
    </h1>
    <nav>
      <ul>
        <li><RouterLink to='/'>Home</RouterLink></li>
        <li><RouterLink to='/courses'>Courses</RouterLink></li>
        <li><RouterLink to='/profile'>Profile</RouterLink></li>
        <li>
          <span class='enrolled-badge'>
            Enrolled: {{ enrollmentStore.enrolledCourses.length }}
          </span>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script setup>
import {RouterLink} from 'vue-router';
import {useEnrollmentStore} from '@/stores/enrollment';

const enrollmentStore=useEnrollmentStore();
</script>

// Module6_FrontendDevelopmentBasics/HandsOn_5/student-portal-react/src/components/header.jsx
import React from 'react';

export default function Header(props){
  return (
    <header>
      <h1>{props.siteName}</h1>
      <nav>
        <ul>
          <li><a href='#courses'>Courses</a></li>
          <li><a href='#profile'>Profile</a></li>
          <li>
            <span class='enrolled-badge'>
              Enrolled: {props.enrolledCount}
            </span>
          </li>
        </ul>
      </nav>
    </header>
  );
}
